ADD Entry resource URL prefix parameter to RDBMS commons and some SQL connectors
GoogleCloudPlatform/datacatalog-connectors-rdbms pull request #55
Opened 2020-11-23 19:37 UTC by mesmacosta

**- What I did**

- Added a new parameter to RDBMS conenctors, so users can specify the entry resource URL prefix.
- Added it to MySQL, PostgreSQL and SQLServer connectors.
- Improved the way the linkedResource is built for Tables and Table containers.
- Improved logging for config classes.
- Added the metadata enricher to All SQL connectors.
- Updated the `__init__` files to use relative imports.

**- How I did it**
The new parameter `datacatalog-entry-resource-url-prefix` overrides the hostname as the entry resource URL prefix when informed:
```
[datacatalog_entry_resource_ur_prefix]/database/table

or when empty
[rbms_host]/database/table
```

**- How to verify it**
Run MySQL, PostgreSQL and SQLServer connectors with the new parameter.

**- Description for the changelog**
ADD Entry resource URL prefix parameter to RDBMS commons and some SQL connectors, fixes #49

2020-11-23 21:01 UTC, ricardolsmendes requested changes
Hi @mesmacosta, I've just left a few comments. Please take a look and let me know your thoughts. Thanks!

2020-11-23 21:01 UTC, ricardolsmendes commented on google-datacatalog-sqlserver-connector/src/google/datacatalog_connectors/sqlserver/datacatalog_cli.py
> +                            help='Entry resource URL prefix'
Same question about the help string...

2020-11-24 11:40 UTC, mesmacosta commented on google-datacatalog-rdbms-connector/src/google/datacatalog_connectors/rdbms/datacatalog_cli.py
> +        # try/except clause for backwards compatibility with
Makes sense it sounds more like as a fallback treatment. I will change the comment.

2020-11-24 11:46 UTC, mesmacosta commented on google-datacatalog-mysql-connector/src/google/datacatalog_connectors/mysql_/datacatalog_cli.py
> +                            help='Entry resource URL prefix'
Thanks for the catch, it was certainly missing.

2020-11-24 14:10 UTC, ricardolsmendes approved these changes
LGTM. Thanks for working on this, @mesmacosta!

2020-11-24 14:12 UTC, merged